vagrant:
  box: parallels/ubuntu-13.10
  box_url: https://vagrantcloud.com/parallels/ubuntu-13.10
  box_port: 80
  box_ip: 10.0.0.123
  ssh_shell: bash -c 'BASH_ENV=/etc/profile exec bash'
  ssh_username: vagrant
  vm_name: cptserver
  vm_memory: 512
  vm_cpu: 80
  vm_webroot: www
  vm_docroot: /var/www
  vm_hostname: localhost
syspackages:
  - build-essential
  - python-software-properties
  - openssl
  - unzip
  - git
  - curl
  - php5-dev
  - php-pear
  - libyaml-dev
apachemodules:
  - rewrite
mysql:
  port: 3306
  password: vagrant
phpmodules:
  - php5-cli
  - php5-mysql
  - php5-sqlite
  - php5-imagick
  - php5-mcrypt
  - php5-imap
  - php5-curl
  - php5-gd
  - php5-xmlrpc
  - php5-xdebug
  - libapache2-mod-php5
xdebug:
  - zend_extension=/usr/lib/php5/20121212/xdebug.so
  - xdebug.remote_enable = 1
  - xdebug.remote_host = localhost
  - xdebug.remote_port = 9000
  - xdebug.remote_connect_back = 1
  - xdebug.remote_handler = dbgp
  - xdebug.remote_mode = req
  - xdebug.remote_log = /tmp/php5-xdebug.log
  - xdebug.profiler_enable = 0
  - xdebug.profiler_output_dir = /tmp
  - xdebug.profiler_output_name = cachegrind.out.%t.%p
rewrite:
  Directory: /var/www/
  Options: Indexes FollowSymLinks MultiViews
  AllowOverride: FileInfo
  Order: allow,deny
  Allow: from all
vhosts:
  -
    ServerName: localhost
    ServerAlias: localhost.dev www.localhost.dev default default.dev www.default.dev
    DocumentRoot: /var/www/default
  -
    ServerName: wordpress.dev
    ServerAlias: www.wordpress.dev
    DocumentRoot: /var/www/wordpress